/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AdminActivityLogs {
  action: string;
  actorUserId: string | null;
  createdAt: Generated<Timestamp>;
  errorMessage: string | null;
  id: Generated<string>;
  payload: Generated<Json>;
  result: string;
  targetUserId: string;
}

export interface Conversations {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  lastMessageAt: Timestamp;
  messageCount: Generated<number>;
  metadata: Generated<Json | null>;
  startedAt: Timestamp;
  status: Generated<string>;
  summary: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface ConversationTopics {
  confidence: number;
  conversationId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  topic: string;
}

export interface FitnessPlans {
  clientId: string;
  createdAt: Generated<Timestamp>;
  currentMesocycleIndex: Generated<number | null>;
  currentMicrocycleWeek: Generated<number | null>;
  cycleStartDate: Timestamp | null;
  goalStatement: string | null;
  id: Generated<string>;
  lengthWeeks: number | null;
  mesocycles: Json | null;
  notes: string | null;
  overview: string | null;
  programType: string;
  startDate: Timestamp;
  updatedAt: Generated<Timestamp>;
}

export interface Messages {
  content: string;
  conversationId: string;
  createdAt: Generated<Timestamp>;
  direction: string;
  id: Generated<string>;
  metadata: Generated<Json | null>;
  phoneFrom: string;
  phoneTo: string;
  twilioMessageSid: string | null;
  userId: string;
}

export interface Microcycles {
  createdAt: Generated<Timestamp>;
  endDate: Timestamp;
  fitnessPlanId: string;
  id: Generated<string>;
  isActive: Generated<boolean | null>;
  mesocycleIndex: number;
  pattern: Json;
  startDate: Timestamp;
  updatedAt: Generated<Timestamp>;
  userId: string;
  weekNumber: number;
}

export interface ProfileUpdates {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  patch: Json;
  path: string | null;
  reason: string | null;
  source: string;
  userId: string;
}

export interface Subscriptions {
  canceledAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  currentPeriodEnd: Timestamp;
  currentPeriodStart: Timestamp;
  id: Generated<string>;
  planType: string;
  status: string;
  stripeSubscriptionId: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string | null;
  id: Generated<string>;
  name: string;
  phoneNumber: string;
  preferredSendHour: Generated<number>;
  profile: Generated<Json | null>;
  stripeCustomerId: string | null;
  timezone: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface WorkoutInstances {
  clientId: string;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  date: Timestamp;
  details: Json;
  fitnessPlanId: string;
  goal: string | null;
  id: Generated<string>;
  mesocycleId: string | null;
  microcycleId: string | null;
  sessionType: string;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  adminActivityLogs: AdminActivityLogs;
  conversations: Conversations;
  conversationTopics: ConversationTopics;
  fitnessPlans: FitnessPlans;
  messages: Messages;
  microcycles: Microcycles;
  profileUpdates: ProfileUpdates;
  subscriptions: Subscriptions;
  users: Users;
  workoutInstances: WorkoutInstances;
}
