version: '3.8'

services:
  postgres-test:
    image: postgres:16-alpine
    container_name: gymtext-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gymtext_test
    ports:
      - "5433:5432"  # Use different port to avoid conflicts with local PostgreSQL
    volumes:
      - gymtext-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  gymtext-test-data: