import { Kysely, sql } from 'kysely';
import { DB } from '../src/server/models/_types';

/**
 * Add message column to workout_instances table
 *
 * This field stores the SMS-formatted workout message generated by the workout agent.
 * When a workout is generated (either during daily message or modification),
 * the message is saved with the workout so it can be reused without regenerating.
 *
 * - message: SMS-formatted workout message for user delivery
 */
export async function up(db: Kysely<DB>): Promise<void> {
  await sql`
    ALTER TABLE workout_instances
    ADD COLUMN message TEXT
  `.execute(db);
}

export async function down(db: Kysely<DB>): Promise<void> {
  await sql`
    ALTER TABLE workout_instances
    DROP COLUMN IF EXISTS message
  `.execute(db);
}
