import { Kysely, sql } from 'kysely';

const AI_OWNER_ID = '00000000-0000-0000-0000-000000000001';
const AI_PROGRAM_ID = '00000000-0000-0000-0000-000000000002';

export async function up(db: Kysely<any>): Promise<void> {
  console.log('Seeding GymText AI program owner...');

  // Create GymText AI owner
  await sql`
    INSERT INTO program_owners (id, user_id, owner_type, display_name, bio, is_active)
    VALUES (
      ${AI_OWNER_ID}::uuid,
      NULL,
      'ai',
      'GymText AI',
      'Your personal AI fitness coach. Creates customized workout plans based on your goals, experience, and schedule.',
      true
    )
    ON CONFLICT (id) DO NOTHING
  `.execute(db);

  console.log('Created GymText AI owner');

  // Create AI Personal Training program
  await sql`
    INSERT INTO programs (id, owner_id, name, description, scheduling_mode, cadence, late_joiner_policy, billing_model, is_active, is_public)
    VALUES (
      ${AI_PROGRAM_ID}::uuid,
      ${AI_OWNER_ID}::uuid,
      'AI Personal Training',
      'Personalized fitness plans generated by AI based on your unique profile, goals, and preferences.',
      'rolling_start',
      'calendar_days',
      'start_from_beginning',
      'subscription',
      true,
      true
    )
    ON CONFLICT (id) DO NOTHING
  `.execute(db);

  console.log('Created AI Personal Training program');
}

export async function down(db: Kysely<any>): Promise<void> {
  await sql`DELETE FROM programs WHERE id = ${AI_PROGRAM_ID}::uuid`.execute(db);
  await sql`DELETE FROM program_owners WHERE id = ${AI_OWNER_ID}::uuid`.execute(db);
}
