/**
 * TEMPORARY STUB FILE
 * 
 * This file provides placeholder types until DATABASE_URL is properly configured
 * and db:codegen can run successfully. Once configured, this file will be 
 * auto-generated by kysely-codegen.
 * 
 * All types are set to 'any' to allow builds to pass without actual database
 * schema information.
 */

// Database schema type
export type DB = any;

// Table types
export type AgentDefinitions = any;
export type AgentExtensions = any;
export type AgentLogs = any;
export type BlogPosts = any;
export type ContextTemplates = any;
export type Conversations = any;
export type DayConfigs = any;
export type ExerciseAliases = any;
export type ExerciseUses = any;
export type Exercises = any;
export type FitnessPlans = any;
export type MessageQueues = any;
export type Messages = any;
export type Microcycles = any;
export type Movements = any;
export type OrganizationMembers = any;
export type Organizations = any;
export type PageVisits = any;
export type ProfileUpdates = any;
export type Profiles = any;
export type ProgramEnrollments = any;
export type ProgramFamilies = any;
export type ProgramFamilyPrograms = any;
export type ProgramOwners = any;
export type ProgramVersions = any;
export type Programs = any;
export type Referrals = any;
export type ShortLinks = any;
export type Subscriptions = any;
export type UploadedImages = any;
export type UserOnboarding = any;
export type Users = any;
export type WorkoutInstances = any;

// Utility types
export type Json = string | number | boolean | null | Json[] | { [key: string]: Json };
export type JsonValue = Json;
