import { createRunnableAgent, initializeModel } from '@/server/agents/base';
import { microcycleStructuredUserPrompt, MICROCYCLE_STRUCTURED_SYSTEM_PROMPT } from './prompt';
import type { StructuredMicrocycleConfig } from './types';
import type { MicrocycleChainContext } from '../generation/chain';
import type { MicrocyclePattern } from '@/server/models/microcycle/schema';

/**
 * Structured Microcycle Agent Factory
 *
 * Converts long-form microcycle descriptions to structured JSON format.
 * Validates the microcycle structure and adds weekIndex.
 *
 * @param config - Static configuration for the agent
 * @returns Agent (runnable) that converts long-form microcycles to structured JSON
 */
export const createStructuredMicrocycleAgent = <TPattern = MicrocyclePattern>(
  config: StructuredMicrocycleConfig
) => {
  // Initialize model with schema from config
  const model = initializeModel(config.schema, config.agentConfig);

  return createRunnableAgent<MicrocycleChainContext, TPattern>(async (input) => {
    const { longFormMicrocycle, weekIndex } = input;

    // Build user prompt from long-form description
    const userPrompt = microcycleStructuredUserPrompt(longFormMicrocycle.description);

    // Invoke model
    const pattern = await model.invoke([
      { role: 'system', content: MICROCYCLE_STRUCTURED_SYSTEM_PROMPT },
      { role: 'user', content: userPrompt }
    ]) as TPattern;

    // Validate the pattern structure
    const validatedPattern = config.schema.parse(pattern);

    console.log(`[${config.operationName}] Generated structured microcycle pattern for week ${weekIndex + 1}`);

    // Add weekIndex deterministically (not generated by AI)
    return {
      ...validatedPattern,
      weekIndex
    } as TPattern;
  });
};
