import type { Message } from './types';

/**
 * Configuration for building messages
 */
export interface BuildMessagesConfig {
  systemPrompt: string;
  userPrompt: string;
  context?: string[];
  previousMessages?: Message[];
}

/**
 * Build the message array for LLM invocation
 * Order: [SYSTEM, ...CONTEXT, ...PREVIOUS, USER]
 *
 * Context messages are added as user role messages between system and conversation history
 *
 * @param config - Message building configuration
 * @returns Array of messages ready for LLM invocation
 */
export function buildMessages(config: BuildMessagesConfig): Message[] {
  const { systemPrompt, userPrompt, context = [], previousMessages = [] } = config;

  // Build context messages (as user messages per existing pattern)
  const contextMessages: Message[] = context
    .filter(content => content && content.trim().length > 0)
    .map(content => ({
      role: 'user' as const,
      content,
    }));

  return [
    { role: 'system', content: systemPrompt },
    ...contextMessages,
    ...previousMessages,
    { role: 'user', content: userPrompt },
  ];
}

/**
 * Build a continuation message for the agentic loop
 * Used after tool execution to prompt the model to continue
 *
 * @param toolType - Type of the last tool executed
 * @param toolMessages - Messages generated by tool execution
 * @returns Continuation message content
 */
export function buildLoopContinuationMessage(
  toolType: 'query' | 'action',
  toolMessages: string[]
): string {
  if (toolType === 'query') {
    return toolMessages.length > 0
      ? `I've retrieved the information. Please provide a helpful response based on this data. Keep it conversational and concise.`
      : `The information has been retrieved. Please respond naturally to my original question.`;
  }

  return toolMessages.length > 0
    ? `The action has been completed. Please provide a brief, natural acknowledgment. Don't repeat what was already said in the tool messages.`
    : `The action has been completed. Please provide a brief, natural acknowledgment.`;
}
