import { createRunnableAgent, initializeModel } from '@/server/agents/base';
import type { StructuredMesocycleInput, StructuredMesocycleContext, MesocycleOutput } from './types';
import { MesocycleOutputSchema } from './types';
import { validateMesocycleOutput } from './validation';
import { STRUCTURED_MESOCYCLE_SYSTEM_PROMPT, structuredMesocycleUserPrompt } from './prompt';
import type { MesocycleAgentConfig } from '../generation/types';

/**
 * Structured Mesocycle Agent Factory
 *
 * Converts mesocycle text into structured JSON with validation.
 *
 * Used as the second step in the mesocycle generation chain to produce structured output
 * from the text generated by the generation agent.
 *
 * Includes validation and retry logic to ensure microcycle count consistency.
 *
 * @param config - Configuration containing (optionally) agent/model settings
 * @returns Agent (runnable) that produces structured mesocycle data from text
 */
export const createStructuredMesocycleAgent = (config: MesocycleAgentConfig) => {
  const model = initializeModel(MesocycleOutputSchema, config.agentConfig);
  const maxRetries = config.maxRetries ?? 3;

  return createRunnableAgent(async (input: StructuredMesocycleInput): Promise<StructuredMesocycleContext> => {
    let lastError: string | undefined;

    const userPrompt = structuredMesocycleUserPrompt(input.mesocycleText);

    for (let attempt = 1; attempt <= maxRetries; attempt++) {
      const mesocycle = await model.invoke([
        { role: 'system', content: STRUCTURED_MESOCYCLE_SYSTEM_PROMPT },
        { role: 'user', content: userPrompt }
      ]) as MesocycleOutput;

      // Validate the output
      const validationResult = validateMesocycleOutput(mesocycle);

      if (validationResult.isValid) {
        console.log(`[StructuredMesocycleAgent] Generated valid structured mesocycle with ${mesocycle.microcycles.length} microcycles`);
        return {
          mesocycle,
          mesocycleOverview: input.mesocycleOverview,
          user: input.user,
        };
      }

      // Validation failed
      lastError = validationResult.error;
      console.warn(`[StructuredMesocycleAgent] Attempt ${attempt}/${maxRetries} failed validation: ${validationResult.error}`);

      // Continue to next attempt if retries remain
      if (attempt < maxRetries) {
        console.log(`[StructuredMesocycleAgent] Retrying structuring...`);
      }
    }

    // All retries exhausted
    throw new Error(`Failed to generate valid structured mesocycle after ${maxRetries} attempts. Last error: ${lastError}`);
  });
};
