import type { Message, AgentExample } from './types';

/**
 * Configuration for building messages
 */
export interface BuildMessagesConfig {
  systemPrompt: string;
  userPrompt: string;
  context?: string[];
  examples?: AgentExample[];
  previousMessages?: Message[];
}

/**
 * Build example messages for few-shot prompting
 *
 * Positive example = 2 messages: user (input) + assistant (output)
 * Negative example = 3 messages: user (input) + assistant (output) + user (correction)
 */
function buildExampleMessages(examples: AgentExample[]): Message[] {
  const messages: Message[] = [];

  for (const example of examples) {
    messages.push({
      role: 'user',
      content: `[EXAMPLE]\n${example.input}`,
      section: 'example',
    });
    messages.push({
      role: 'assistant',
      content: example.output,
      section: 'example',
    });
    if (example.type === 'negative' && example.feedback) {
      messages.push({
        role: 'user',
        content: `[CORRECTION] ${example.feedback}`,
        section: 'example',
      });
    }
  }

  return messages;
}

/**
 * Build the message array for LLM invocation
 * Order: [SYSTEM, ...CONTEXT, ...EXAMPLES, ...PREVIOUS, USER]
 *
 * Context messages are added as user role messages between system and conversation history.
 * Examples are injected as user/assistant pairs between context and previous messages.
 *
 * @param config - Message building configuration
 * @returns Array of messages ready for LLM invocation
 */
export function buildMessages(config: BuildMessagesConfig): Message[] {
  const { systemPrompt, userPrompt, context = [], examples, previousMessages = [] } = config;

  // Build context messages (as user messages per existing pattern)
  const contextMessages: Message[] = context
    .filter(content => content && content.trim().length > 0)
    .map(content => ({
      role: 'user' as const,
      content,
      section: 'context' as const,
    }));

  // Build example messages for few-shot prompting (already tagged in buildExampleMessages)
  const exampleMessages: Message[] = examples && examples.length > 0
    ? buildExampleMessages(examples)
    : [];

  return [
    { role: 'system', content: systemPrompt, section: 'system' as const },
    ...contextMessages,
    ...exampleMessages,
    ...previousMessages.map(m => ({ ...m, section: m.section ?? 'previous' as const })),
    { role: 'user', content: userPrompt, section: 'user' as const },
  ];
}

/**
 * Build a continuation message for the agentic loop
 * Used after tool execution to prompt the model to continue
 *
 * Provides type-aware instructions and warns about automated messages
 * to help the model generate natural, non-repetitive responses.
 *
 * @param toolType - Type of the last tool executed ('query' or 'action')
 * @param toolMessages - Messages generated by tool execution (will be sent after response)
 * @returns Continuation message content
 */
export function buildLoopContinuationMessage(
  toolType: 'query' | 'action',
  toolMessages: string[]
): string {
  let messageContext = '';
  if (toolMessages.length > 0) {
    messageContext = `
[AUTOMATED MESSAGES]
The following messages will be sent to the user immediately after your response:
${toolMessages.map((m) => `- "${m.substring(0, 100)}${m.length > 100 ? '...' : ''}"`).join('\n')}
`;
  }

  if (toolType === 'query') {
    // QUERY tool - user asked for information
    return `[SYSTEM: TOOL COMPLETE - QUERY]
${messageContext}
[INSTRUCTION]
The user asked a question and you retrieved the answer.
- Provide a brief, natural intro to the information (e.g., "Here's your workout for today:" or "Today you've got [type]:")
- DO NOT say "Done" or "Complete" - this was a question, not a request for action
- If [AUTOMATED MESSAGES] are listed, they contain the detailed response. Just provide a smooth lead-in.
- If there was an error, explain it simply.
- Keep it conversational and SMS-style (1-2 sentences max).
`;
  }

  // ACTION tool - user requested a change
  return `[SYSTEM: TOOL COMPLETE - ACTION]
${messageContext}
[INSTRUCTION]
The user requested a change and it has been processed.
- Briefly confirm what was done in a natural way
- If [AUTOMATED MESSAGES] are listed, DO NOT repeat their content. Just provide a brief confirmation.
- If you called make_modification with a message, that acknowledgment was already sent. Focus on the result now.
- If the action failed, explain the issue simply.
- Keep it conversational and SMS-style (1-2 sentences max).
`;
}
