/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Conversations {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  lastMessageAt: Timestamp;
  messageCount: Generated<number>;
  metadata: Generated<Json | null>;
  startedAt: Timestamp;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface ConversationTopics {
  confidence: number;
  conversationId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  topic: string;
}

export interface FitnessProfiles {
  age: number;
  createdAt: Generated<Timestamp>;
  exerciseFrequency: string;
  fitnessGoals: string;
  gender: string;
  id: Generated<string>;
  skillLevel: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Messages {
  content: string;
  conversationId: string;
  createdAt: Generated<Timestamp>;
  direction: string;
  id: Generated<string>;
  metadata: Generated<Json | null>;
  phoneFrom: string;
  phoneTo: string;
  twilioMessageSid: string | null;
  userId: string;
}

export interface Subscriptions {
  canceledAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  currentPeriodEnd: Timestamp;
  currentPeriodStart: Timestamp;
  id: Generated<string>;
  planType: string;
  status: string;
  stripeSubscriptionId: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string | null;
  id: Generated<string>;
  name: string;
  phoneNumber: string;
  stripeCustomerId: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface WorkoutLogs {
  completed: Generated<boolean>;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  feedback: string | null;
  id: Generated<string>;
  rating: number | null;
  userId: string;
  workoutId: string;
}

export interface Workouts {
  createdAt: Generated<Timestamp>;
  date: Timestamp;
  exercises: Json;
  id: Generated<string>;
  sentAt: Timestamp | null;
  userId: string;
  workoutType: string;
}

export interface DB {
  conversations: Conversations;
  conversationTopics: ConversationTopics;
  fitnessProfiles: FitnessProfiles;
  messages: Messages;
  subscriptions: Subscriptions;
  users: Users;
  workoutLogs: WorkoutLogs;
  workouts: Workouts;
}
