/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Conversations {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_message_at: Timestamp;
  message_count: Generated<number>;
  metadata: Generated<Json | null>;
  started_at: Timestamp;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface ConversationTopics {
  confidence: number;
  conversation_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  topic: string;
}

export interface FitnessProfiles {
  age: number;
  created_at: Generated<Timestamp>;
  exercise_frequency: string;
  fitness_goals: string;
  gender: string;
  id: Generated<string>;
  skill_level: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Messages {
  content: string;
  conversation_id: string;
  created_at: Generated<Timestamp>;
  direction: string;
  id: Generated<string>;
  metadata: Generated<Json | null>;
  phone_from: string;
  phone_to: string;
  twilio_message_sid: string | null;
  user_id: string;
}

export interface ProgramPhases {
  created_at: Generated<Timestamp>;
  description: string | null;
  end_week: number;
  focus: string | null;
  id: Generated<string>;
  name: string;
  phase_number: number;
  program_id: string;
  start_week: number;
  training_variables: Json | null;
}

export interface ProgramSessions {
  created_at: Generated<Timestamp>;
  day_of_week: number;
  description: string | null;
  duration_minutes: number | null;
  exercises: Json | null;
  id: Generated<string>;
  name: string | null;
  session_type: string | null;
  week_id: string;
}

export interface ProgramTemplates {
  category: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  equipment_required: Json | null;
  experience_level: string | null;
  id: Generated<string>;
  is_public: Generated<boolean | null>;
  name: string;
  template_data: Json;
}

export interface ProgramWeeks {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  name: string | null;
  phase_id: string | null;
  program_id: string;
  training_split: Json | null;
  week_number: number;
  weekly_volume_target: Json | null;
}

export interface Subscriptions {
  canceled_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  current_period_end: Timestamp;
  current_period_start: Timestamp;
  id: Generated<string>;
  plan_type: string;
  status: string;
  stripe_subscription_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface UserPrograms {
  adaptations: Json | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  current_phase_id: string | null;
  current_week: Generated<number | null>;
  id: Generated<string>;
  program_id: string;
  started_at: Generated<Timestamp>;
  status: Generated<string | null>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string | null;
  id: Generated<string>;
  name: string;
  phone_number: string;
  stripe_customer_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface WorkoutLogs {
  completed: Generated<boolean>;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  feedback: string | null;
  id: Generated<string>;
  rating: number | null;
  user_id: string;
  workout_id: string;
}

export interface WorkoutPrograms {
  created_at: Generated<Timestamp>;
  description: string | null;
  duration_type: string | null;
  duration_weeks: number | null;
  end_date: Timestamp | null;
  equipment_required: Json | null;
  goals: Json | null;
  id: Generated<string>;
  name: string;
  program_type: string | null;
  start_date: Timestamp | null;
  status: Generated<string | null>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Workouts {
  created_at: Generated<Timestamp>;
  date: Timestamp;
  exercises: Json;
  id: Generated<string>;
  program_session_id: string | null;
  sent_at: Timestamp | null;
  user_id: string;
  user_program_id: string | null;
  workout_type: string;
}

export interface DB {
  conversation_topics: ConversationTopics;
  conversations: Conversations;
  fitness_profiles: FitnessProfiles;
  messages: Messages;
  program_phases: ProgramPhases;
  program_sessions: ProgramSessions;
  program_templates: ProgramTemplates;
  program_weeks: ProgramWeeks;
  subscriptions: Subscriptions;
  user_programs: UserPrograms;
  users: Users;
  workout_logs: WorkoutLogs;
  workout_programs: WorkoutPrograms;
  workouts: Workouts;
}
