/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AdminActivityLogs {
  action: string;
  actorClientId: string | null;
  createdAt: Generated<Timestamp>;
  errorMessage: string | null;
  id: Generated<string>;
  payload: Generated<Json>;
  result: string;
  targetClientId: string;
}

export interface AgentDefinitions {
  agentId: string;
  createdAt: Generated<Timestamp>;
  description: string | null;
  evalRubric: string | null;
  examples: Json | null;
  hooks: Json | null;
  isActive: Generated<boolean>;
  maxIterations: Generated<number | null>;
  maxTokens: Generated<number | null>;
  model: Generated<string>;
  systemPrompt: string;
  temperature: Generated<Numeric | null>;
  toolHooks: Json | null;
  toolIds: string[] | null;
  userPromptTemplate: string | null;
  versionId: Generated<number>;
}

export interface AgentLogs {
  agentId: string;
  createdAt: Generated<Timestamp>;
  durationMs: number | null;
  id: Generated<string>;
  input: string | null;
  messages: Json;
  metadata: Generated<Json | null>;
  model: string | null;
  response: Json | null;
}

export interface BlogPosts {
  content: string;
  coverImageId: string | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  metaDescription: string | null;
  metaTitle: string | null;
  organizationId: string | null;
  ownerId: string;
  publishedAt: Timestamp | null;
  readingTimeMinutes: number | null;
  slug: string;
  status: Generated<string>;
  tags: Generated<Json | null>;
  title: string;
  updatedAt: Generated<Timestamp>;
  viewCount: Generated<number>;
}

export interface DayConfigs {
  config: Generated<Json>;
  createdAt: Generated<Timestamp>;
  date: Timestamp;
  id: Generated<string>;
  scopeId: string | null;
  scopeType: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface EventLogs {
  chainId: string | null;
  createdAt: Generated<Timestamp | null>;
  data: Generated<Json | null>;
  entityId: string | null;
  eventName: string;
  id: Generated<string>;
  userId: string | null;
}

export interface ExerciseAliases {
  alias: string;
  aliasLex: Generated<string>;
  aliasNormalized: string;
  confidenceScore: Numeric | null;
  createdAt: Generated<Timestamp>;
  exerciseId: string;
  id: Generated<string>;
  isDefault: Generated<boolean>;
  source: Generated<string>;
}

export interface Exercises {
  aliases: Generated<string[]>;
  createdAt: Generated<Timestamp>;
  cues: Generated<string[]>;
  embedding: string | null;
  embeddingText: string | null;
  embeddingTextVersion: Generated<number | null>;
  equipment: Generated<string[]>;
  id: Generated<string>;
  instructions: Generated<string>;
  intensity: Generated<string | null>;
  isActive: Generated<boolean>;
  mechanics: Generated<string | null>;
  modality: Generated<string | null>;
  movementId: string | null;
  movementPatterns: Generated<string[]>;
  name: string;
  popularity: Generated<Numeric>;
  primaryMuscles: Generated<string[]>;
  secondaryMuscles: Generated<string[]>;
  shortDescription: Generated<string>;
  slug: string;
  status: Generated<string>;
  trainingGroups: Generated<string[]>;
  type: string;
  updatedAt: Generated<Timestamp>;
}

export interface ExerciseUses {
  createdAt: Generated<Timestamp>;
  exerciseId: string;
  id: Generated<string>;
  userId: string | null;
  useType: string;
}

export interface FitnessPlans {
  clientId: string;
  content: string | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  startDate: Timestamp;
}

export interface MessageQueues {
  clientId: string;
  createdAt: Generated<Timestamp>;
  errorMessage: string | null;
  id: Generated<string>;
  maxRetries: Generated<number>;
  messageId: string;
  processedAt: Timestamp | null;
  queueName: string;
  retryCount: Generated<number>;
  sequenceNumber: number;
  status: Generated<string>;
}

export interface Messages {
  clientId: string;
  content: string;
  createdAt: Generated<Timestamp>;
  deliveryAttempts: Generated<number>;
  deliveryError: string | null;
  deliveryStatus: Generated<string>;
  direction: string;
  id: Generated<string>;
  lastDeliveryAttemptAt: Timestamp | null;
  metadata: Generated<Json | null>;
  phoneFrom: string | null;
  phoneTo: string | null;
  provider: Generated<string>;
  providerMessageId: string | null;
}

export interface Microcycles {
  clientId: string;
  content: string | null;
  createdAt: Generated<Timestamp>;
  details: Json | null;
  id: Generated<string>;
  message: string | null;
  planId: string | null;
  startDate: Timestamp;
}

export interface Movements {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  metricType: Generated<string>;
  name: string;
  parentSlug: string | null;
  slug: string;
  updatedAt: Generated<Timestamp>;
}

export interface OrganizationMembers {
  id: Generated<string>;
  joinedAt: Generated<Timestamp>;
  organizationId: string;
  programOwnerId: string;
  role: Generated<string>;
}

export interface Organizations {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  isActive: Generated<boolean>;
  logoUrl: string | null;
  name: string;
  organizationType: string | null;
  slug: string;
  updatedAt: Generated<Timestamp>;
  websiteUrl: string | null;
  wordmarkUrl: string | null;
}

export interface PageVisits {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  ipAddress: string | null;
  page: string;
  referrer: string | null;
  source: string | null;
  userAgent: string | null;
  utmCampaign: string | null;
  utmContent: string | null;
  utmMedium: string | null;
  utmSource: string | null;
  utmTerm: string | null;
}

export interface Profiles {
  clientId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  profile: string;
}

export interface ProfileUpdates {
  clientId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  patch: Json;
  path: string | null;
  reason: string | null;
  source: string;
}

export interface ProgramEnrollments {
  clientId: string;
  cohortId: string | null;
  cohortStartDate: Timestamp | null;
  createdAt: Generated<Timestamp>;
  currentWeek: Generated<number>;
  enrolledAt: Generated<Timestamp>;
  id: Generated<string>;
  programId: string;
  programVersionId: string | null;
  startDate: Timestamp;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface ProgramFamilies {
  createdAt: Generated<Timestamp>;
  description: string | null;
  familyType: string;
  id: Generated<string>;
  name: string;
  ownerId: string | null;
  slug: string;
  visibility: Generated<string>;
}

export interface ProgramFamilyPrograms {
  familyId: string;
  pinned: Generated<boolean>;
  programId: string;
  role: string | null;
  sortOrder: Generated<number>;
}

export interface ProgramOwners {
  avatarUrl: string | null;
  bio: string | null;
  createdAt: Generated<Timestamp>;
  displayName: string;
  id: Generated<string>;
  isActive: Generated<boolean>;
  ownerType: string;
  phone: string | null;
  slug: string | null;
  stripeConnectAccountId: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string | null;
  wordmarkUrl: string | null;
}

export interface Programs {
  billingModel: Generated<string | null>;
  cadence: Generated<string>;
  coverImageId: string | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  isActive: Generated<boolean>;
  isPublic: Generated<boolean>;
  lateJoinerPolicy: Generated<string | null>;
  name: string;
  organizationId: string | null;
  ownerId: string;
  publishedVersionId: string | null;
  revenueSplitPercent: Generated<number | null>;
  schedulingMode: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface ProgramVersions {
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  defaultDurationWeeks: number | null;
  difficultyMetadata: Json | null;
  generationConfig: Json | null;
  id: Generated<string>;
  programId: string;
  publishedAt: Timestamp | null;
  questions: Json | null;
  status: Generated<string>;
  templateMarkdown: string | null;
  templateStructured: Json | null;
  versionNumber: number;
}

export interface Referrals {
  createdAt: Generated<Timestamp>;
  creditAmountCents: Generated<number | null>;
  creditApplied: Generated<boolean>;
  creditedAt: Timestamp | null;
  id: Generated<string>;
  refereeId: string;
  referrerId: string;
}

export interface ShortLinks {
  accessCount: Generated<number>;
  clientId: string | null;
  code: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  lastAccessedAt: Timestamp | null;
  targetPath: string;
}

export interface Subscriptions {
  canceledAt: Timestamp | null;
  clientId: string;
  createdAt: Generated<Timestamp>;
  currentPeriodEnd: Timestamp;
  currentPeriodStart: Timestamp;
  id: Generated<string>;
  planType: string;
  status: string;
  stripeSubscriptionId: string;
  updatedAt: Generated<Timestamp>;
}

export interface UploadedImages {
  category: Generated<string | null>;
  contentType: string;
  createdAt: Generated<Timestamp>;
  displayName: string | null;
  filename: string;
  id: Generated<string>;
  sizeBytes: number;
  tags: Generated<Json | null>;
  uploadedBy: string | null;
  url: string;
}

export interface UserAuthCodes {
  code: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  phoneNumber: string;
}

export interface UserExerciseMetrics {
  clientId: string;
  createdAt: Generated<Timestamp>;
  data: Json;
  exerciseId: string;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
  workoutId: string;
}

export interface UserOnboarding {
  clientId: string;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  currentStep: number | null;
  errorMessage: string | null;
  id: Generated<string>;
  programMessagesSent: Generated<boolean | null>;
  signupData: Json | null;
  startedAt: Timestamp | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Users {
  age: number | null;
  createdAt: Generated<Timestamp>;
  email: string | null;
  gender: string | null;
  id: Generated<string>;
  messagingOptIn: Generated<boolean | null>;
  messagingOptInDate: Timestamp | null;
  name: string;
  phoneNumber: string;
  preferredMessagingProvider: Generated<string | null>;
  preferredSendHour: Generated<number>;
  referralCode: string | null;
  stripeCustomerId: string | null;
  timezone: Generated<string>;
  units: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface WorkoutInstances {
  clientId: string;
  createdAt: Generated<Timestamp>;
  date: Timestamp;
  details: Json | null;
  id: Generated<string>;
  message: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  adminActivityLogs: AdminActivityLogs;
  agentDefinitions: AgentDefinitions;
  agentLogs: AgentLogs;
  blogPosts: BlogPosts;
  dayConfigs: DayConfigs;
  eventLogs: EventLogs;
  exerciseAliases: ExerciseAliases;
  exercises: Exercises;
  exerciseUses: ExerciseUses;
  fitnessPlans: FitnessPlans;
  messageQueues: MessageQueues;
  messages: Messages;
  microcycles: Microcycles;
  movements: Movements;
  organizationMembers: OrganizationMembers;
  organizations: Organizations;
  pageVisits: PageVisits;
  profiles: Profiles;
  profileUpdates: ProfileUpdates;
  programEnrollments: ProgramEnrollments;
  programFamilies: ProgramFamilies;
  programFamilyPrograms: ProgramFamilyPrograms;
  programOwners: ProgramOwners;
  programs: Programs;
  programVersions: ProgramVersions;
  referrals: Referrals;
  shortLinks: ShortLinks;
  subscriptions: Subscriptions;
  uploadedImages: UploadedImages;
  userAuthCodes: UserAuthCodes;
  userExerciseMetrics: UserExerciseMetrics;
  userOnboarding: UserOnboarding;
  users: Users;
  workoutInstances: WorkoutInstances;
}
