/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AdminActivityLogs {
  action: string;
  actorClientId: string | null;
  createdAt: Generated<Timestamp>;
  errorMessage: string | null;
  id: Generated<string>;
  payload: Generated<Json>;
  result: string;
  targetClientId: string;
}

export interface DayConfigs {
  config: Generated<Json>;
  createdAt: Generated<Timestamp>;
  date: Timestamp;
  id: Generated<string>;
  scopeId: string | null;
  scopeType: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface FitnessPlans {
  clientId: string;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  message: string | null;
  startDate: Timestamp;
  structured: Json | null;
  updatedAt: Generated<Timestamp>;
}

export interface MessageQueues {
  clientId: string;
  createdAt: Generated<Timestamp>;
  deliveredAt: Timestamp | null;
  errorMessage: string | null;
  id: Generated<string>;
  maxRetries: Generated<number>;
  mediaUrls: Json | null;
  messageContent: string | null;
  messageId: string | null;
  queueName: string;
  retryCount: Generated<number>;
  sentAt: Timestamp | null;
  sequenceNumber: number;
  status: Generated<string>;
  timeoutMinutes: Generated<number>;
}

export interface Messages {
  clientId: string;
  content: string;
  conversationId: string | null;
  createdAt: Generated<Timestamp>;
  deliveryAttempts: Generated<number>;
  deliveryError: string | null;
  deliveryStatus: Generated<string>;
  direction: string;
  id: Generated<string>;
  lastDeliveryAttemptAt: Generated<Timestamp | null>;
  metadata: Generated<Json | null>;
  phoneFrom: string | null;
  phoneTo: string | null;
  provider: Generated<string>;
  providerMessageId: string | null;
}

export interface Microcycles {
  absoluteWeek: Generated<number>;
  clientId: string;
  createdAt: Generated<Timestamp>;
  days: string[] | null;
  description: string | null;
  endDate: Timestamp;
  id: Generated<string>;
  isActive: Generated<boolean | null>;
  isDeload: Generated<boolean>;
  message: string | null;
  startDate: Timestamp;
  structured: Json | null;
  updatedAt: Generated<Timestamp>;
}

export interface NeonAuthUsersSync {
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  email: Generated<string | null>;
  id: Generated<string>;
  name: Generated<string | null>;
  rawJson: Json;
  updatedAt: Timestamp | null;
}

export interface PageVisits {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  ipAddress: string | null;
  page: string;
  referrer: string | null;
  source: string | null;
  userAgent: string | null;
  utmCampaign: string | null;
  utmContent: string | null;
  utmMedium: string | null;
  utmSource: string | null;
  utmTerm: string | null;
}

export interface Profiles {
  clientId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  profile: string;
  structured: Json | null;
}

export interface ProfileUpdates {
  clientId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  patch: Json;
  path: string | null;
  reason: string | null;
  source: string;
}

export interface Prompts {
  createdAt: Generated<Timestamp>;
  id: string;
  role: string;
  value: string;
}

export interface Referrals {
  createdAt: Generated<Timestamp>;
  creditAmountCents: Generated<number | null>;
  creditApplied: Generated<boolean>;
  creditedAt: Timestamp | null;
  id: Generated<string>;
  refereeId: string;
  referrerId: string;
}

export interface ShortLinks {
  accessCount: Generated<number>;
  clientId: string | null;
  code: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  lastAccessedAt: Timestamp | null;
  targetPath: string;
}

export interface Subscriptions {
  canceledAt: Timestamp | null;
  clientId: string;
  createdAt: Generated<Timestamp>;
  currentPeriodEnd: Timestamp;
  currentPeriodStart: Timestamp;
  id: Generated<string>;
  planType: string;
  status: string;
  stripeSubscriptionId: string;
  updatedAt: Generated<Timestamp>;
}

export interface UploadedImages {
  category: Generated<string | null>;
  contentType: string;
  createdAt: Generated<Timestamp>;
  displayName: string | null;
  filename: string;
  id: Generated<string>;
  sizeBytes: number;
  tags: Generated<Json | null>;
  uploadedBy: string | null;
  url: string;
}

export interface UserAuthCodes {
  code: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  phoneNumber: string;
}

export interface UserOnboarding {
  clientId: string;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  currentStep: number | null;
  errorMessage: string | null;
  id: Generated<string>;
  programMessagesSent: Generated<boolean | null>;
  signupData: Json | null;
  startedAt: Timestamp | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Users {
  age: number | null;
  createdAt: Generated<Timestamp>;
  email: string | null;
  gender: string | null;
  id: Generated<string>;
  name: string;
  phoneNumber: string;
  preferredSendHour: Generated<number>;
  referralCode: string | null;
  stripeCustomerId: string | null;
  timezone: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface WorkoutInstances {
  clientId: string;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  date: Timestamp;
  description: string | null;
  details: Json;
  goal: string | null;
  id: Generated<string>;
  message: string | null;
  microcycleId: string | null;
  reasoning: string | null;
  sessionType: string;
  structured: Json | null;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  adminActivityLogs: AdminActivityLogs;
  dayConfigs: DayConfigs;
  fitnessPlans: FitnessPlans;
  messageQueues: MessageQueues;
  messages: Messages;
  microcycles: Microcycles;
  "neonAuth.usersSync": NeonAuthUsersSync;
  pageVisits: PageVisits;
  profiles: Profiles;
  profileUpdates: ProfileUpdates;
  prompts: Prompts;
  referrals: Referrals;
  shortLinks: ShortLinks;
  subscriptions: Subscriptions;
  uploadedImages: UploadedImages;
  userAuthCodes: UserAuthCodes;
  userOnboarding: UserOnboarding;
  users: Users;
  workoutInstances: WorkoutInstances;
}
